#!/usr/bin/env python3


# This script is used for abstracting cfg files generated by the cfg.py script
# Author: Buster Major


import networkx as nx
import re


# IMPORTS #


def abstract_if(cfg):
    a = 1
    # fnefcv


# todo: main method which reads contents of directory


if __name__ == '__main__':
    g = nx.drawing.nx_pydot.read_dot('C:\\Users\\Buster\\Desktop\\ex30.py.dot')
    attributes = nx.get_node_attributes(g, 'label')
    regexp = re.compile(r'')
    for e in attributes:

        # regex for regular ifs: 'if\s+((?!(\"\:\")).*):' use first capturing group
        # regex for one line if elses: 'if\s+((?!(\"else\")).*)\s+else'
        print(attributes[e])




